[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
futures = "0.3.30"
serialport = "4.3.0"
tokio = { version = "1.38.0", features = ["full"] }
tokio-serial = "5.4.4"
